server:
    port: ${random.int[10000,10010]}
application:
  websocket:
    session:
      end-point: websocket
      allowed-origin: "*"
      destination-prefix: /topic
      user-destination-prefix: /user
      test-destination-prefix: /test
      application-destination-prefix: /app
      relay-port: ${random.int[20000,210000]}
      ticket-key: ticket
      server-heart-beat-frequency: 5000
      client-heart-beat-frequency: 0
      anonymous-topic-set: [
              "${application.websocket.session.destination-prefix}/sync/time",
      ]
